### ISSUE TITLE
Improper reference to API 23 in a common method causes crash on API < 23

### ISSUE THREAD

**Issue by tvierling** [XspeedPL/XSharedLibrary#1]
XSharedLibrary/src/xeed/library/view/TextSeekBar.java has the following:

``` java
    @TargetApi(23)
    @SuppressWarnings("deprecation")
    public final void setTextAppearance(final int resId)
    {
        if (Build.VERSION.SDK_INT > 22) mAttrs.setTextAppearance(resId);
        else mAttrs.setTextAppearance(getContext(), resId);
        mPaint.setColor(mAttrs.getCurrentTextColor());
        mPaint.setTextSize(mAttrs.getTextSize());
        mPaint.setTypeface(mAttrs.getTypeface());
    }
```

This method is intended to provide backwards compatibility with API < 23 (6.0/Marshmallow) but does it incorrectly. As written, for instance, when trying to edit an entry in Physical Button Music Control, there is an instant crash which begins with:

```
07-05 12:05:38.138 14620 14620 I dalvikvm: Could not find method android.widget.TextView.setTextAppearance, referenced from method xeed.library.view.TextSeekBar.setTextAppearance
07-05 12:05:38.138 14620 14620 W dalvikvm: VFY: unable to resolve virtual method 8333: Landroid/widget/TextView;.setTextAppearance (I)V
07-05 12:05:38.138 14620 14620 D dalvikvm: VFY: replacing opcode 0x6e at 0x0008
07-05 12:05:38.138 14620 14620 E InputEventReceiver: Exception dispatching input event.
07-05 12:05:38.138 14620 14620 E MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
07-05 12:05:38.158 14620 14620 E MessageQueue-JNI: android.view.InflateException: Binary XML file line #113: Error inflating class xeed.library.view.TextSeekBar
07-05 12:05:38.158 14620 14620 E MessageQueue-JNI:  at android.view.LayoutInflater.createView(LayoutInflater.java:613)
...
```

This happens because the API 23 new method, TextView.setTextAppearance(int), is called right there, and the class loader is trying to link to that when TextSeekBar.setTextAppearance(int) executes. This fails because older devices don't have that method

The correct way to provide this compatibility is a set of two methods, one for the basic functionality, and one as a trampoline to the newer API method. To do this:
- remove the `@TargetApi(23)` from `setTextAppearance(int)`
- create a new, private method which calls `mAttrs.setTextAppearance(resId);` and is set to `@TargetApi(23)`
- replace the call in the `if`-statement to a call to this method.

This removes the link time dependency and allows the class to link properly on pre-6.0 devices. For example:

``` java
    @SuppressWarnings("deprecation")
    public final void setTextAppearance(final int resId)
    {
        if (Build.VERSION.SDK_INT > 22) setTextAppearanceMM(resId);
        else mAttrs.setTextAppearance(getContext(), resId);
        mPaint.setColor(mAttrs.getCurrentTextColor());
        mPaint.setTextSize(mAttrs.getTextSize());
        mPaint.setTypeface(mAttrs.getTypeface());
    }

    @TargetApi(23)
    private void setTextAppearanceMM(final int resId)
    {
        mAttrs.setTextAppearance(resId);
    }
```

**Comment by tvierling** [comment]
Though I could also point out that using the deprecated method shouldn't _break_ on API 23+; it just forwards to the new method there. (So the simplest fix could be to remove the call to the new method entirely, and just use the old one anyway.)

**Comment by XspeedPL** [comment]
Well, my current understanding of bytecode was that if something is not being called, it isn't going to be loaded.
I guess I was mistaken.

Thanks for the report.

**Comment by tvierling** [comment]
That's true at a method level. When a method executes for the first time, it links all potential call-outs from that method before running the first instruction. This is necessary for JIT to work properly.

That's why the split configuration I show above works; it can successfully link to the private setTextAppearanceMM() trampoline method. But, since older devices never call that method, the linkage to the new API 23 call (inside the trampoline method) is never performed.
